load "environment.rb"

Vagrant.configure('2') do |config|
  (1..3).each do |i|
    config.vm.define "dev-station-#{i}" do |config|
        config.vm.provider :digital_ocean do |provider, override|
          override.ssh.private_key_path = '~/.ssh/id_rsa'
          override.vm.box = 'digital_ocean'
          override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
          override.nfs.functional = false
          override.vm.allowed_synced_folder_types = :rsync
          provider.token = $token
          provider.image = 'debian-12-x64'
          case i
          when 3 then
            provider.region = 'fra1'
          end
          provider.region = 'sfo3'
          provider.size = 's-1vcpu-1gb'
          provider.backups_enabled = false
          provider.private_networking = false
          provider.ipv6 = false
          provider.monitoring = false
        end
        config.vm.provision "shell", path: "dev_station_bootstrap.sh", privileged: true
    end
  end
end
